import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { test } from "node:test";
import { getCheckoutGraphData, getCheckoutCommitPage } from "../commands/graph/data.mjs";

const exec = promisify(execFile);

test("graph and pagination omit obsolete detached worker versions but retain refs and local HEAD", async t => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "tb-graph-worktrees-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const root = path.join(directory, "repo");
  const git = async (...args) => (await exec("git", args, { cwd: root })).stdout.trim();
  await exec("git", ["init", "-b", "main", root]);
  await git("config", "user.name", "Test");
  await git("config", "user.email", "test@example.invalid");
  await git("config", "commit.gpgsign", "false");
  await git("commit", "--allow-empty", "-m", "Base");
  await git("switch", "-c", "patch");
  await git("commit", "--allow-empty", "-m", "Old patch");
  const old = await git("rev-parse", "HEAD");
  await git("worktree", "add", "--detach", path.join(directory, "worker"), old);
  await git("commit", "--amend", "--allow-empty", "-m", "Current patch");
  const current = await git("rev-parse", "HEAD");
  await git("switch", "-c", "tb-try-fixup/test");
  await git("commit", "--allow-empty", "-m", "Current fixup");
  const fixup = await git("rev-parse", "HEAD");
  await git("switch", "--detach", current);
  await git("commit", "--allow-empty", "-m", "Local detached work");
  const local = await git("rev-parse", "HEAD");
  assert.match(await git("log", "--all", "--format=%H"), new RegExp(old));
  await git("update-ref", "refs/tb-tools/repair-history/old", old);
  await git("update-ref", "refs/tb-tools/repair-owners/old", old);
  const worker = path.join(directory, "worker");
  await git("-C", worker, "commit", "--allow-empty", "-m", "Private validation copy");
  const validation = await git("-C", worker, "rev-parse", "HEAD");
  await git("update-ref", "refs/tb-tools/try-validation/test", validation);
  const runCommand = async ({ cmd, args, cwd }) => (await exec(cmd, args, { cwd })).stdout;
  const graph = await getCheckoutGraphData({ cwd: root, label: "test", diffs: false, limit: 20, runCommand });
  assert.equal(graph.error, undefined);
  assert.equal(graph.commits.some(commit => commit.hash === old), false);
  assert.equal(graph.commits.some(commit => commit.hash === validation), false);
  for (const hash of [current, fixup, local]) assert.ok(graph.commits.some(commit => commit.hash === hash));
  const page = await getCheckoutCommitPage({ cwd: root, limit: 2, offset: 1, runCommand });
  const expected = (await git("log", "--single-worktree", "--exclude=refs/tb-tools/repair-history/*", "--exclude=refs/tb-tools/repair-owners/*", "--exclude=refs/tb-tools/try-validation/*", "--all", "--topo-order", "--skip=1", "--max-count=2", "--format=%H")).split("\n");
  assert.deepEqual(page.commits.map(commit => commit.hash), expected);
  assert.equal(await git("-C", path.join(directory, "worker"), "rev-parse", "HEAD"), validation);
});
